version: '3.8'
services:

  nginx:
    env_file: .env
    image: nginx:1.9.6
    volumes:
    - ./www:/var/www:rw
    - ./app:/app
    - ./console:/console
    - ./ci/dev/nginx/conf.d:/etc/nginx/conf.d
    - ./logs/nginx/:/var/log/nginx
    ports:
    - "80:80"
    - "443:443"
#    depends_on:
#      core:
#        condition: service_healthy
    depends_on:
      - php
    networks:
      - legacy


  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "$DATABASE_ROOT_PASSWORD"
      MYSQL_DATABASE: "$DATABASE_NAME"
    volumes:
      - ./ci/dev/mysql/mysql:/var/lib/mysql
    networks:
      - legacy

  php:
    build: ./ci/dev/php
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
    - ./www:/var/www:rw
    - ./ci/dev/php/config/php.ini:/usr/local/etc/php/php.ini:rw
    - ./ci/dev/php/config/xdebug:/usr/local/etc/php/xdebug:rw
    working_dir: /var/www/
    ports:
    - "9000:9000"
    depends_on:
    - mysql
    environment:
    - ICU_DATA=/opt/icu/
    networks:
      - legacy


volumes:
  control:
    driver: local
  esdata:
  dbdata:

networks:
  legacy:
